### ISSUE TITLE
@NgModule annotation issue

### ISSUE THREAD

**Issue by balvinder294** [sarfarazansari/ng-social-login-module#1]
Hi there i integrated this package in one of our application and it works fine on dev profile , but there is an error for prod profile build .
Unexpected value 'SocialLoginModule in app/node_modules/ng-social-login-module/ng-social-login-module.d.ts' imported by the module 'DehazeAccountModule in app/src/main/webapp/app/account/account.module.ts'. Please add a @NgModule annotation.

Can you help with this issue or suggest how we can fix, as this is a node module and we can not change manually every time...

**Comment by sarfarazansari** [comment]
@balvinder294 thanks for reporting the issue.
I've fixed the issue in [commit](https://github.com/sarfarazansari/ng-social-login-module/commit/7821cdd39c5aacb1a7d2f2ec86661e12a88ea066).

and publish the updated package on npm.
so kindly please update package to `1.0.4`

**Comment by balvinder294** [comment]
Thanks... for the fix, you saved my day

**Comment by balvinder294** [comment]
I tried by updating the package, still same error in prod environment, can you help if any changes needed to be done along updating package?

**Comment by balvinder294** [comment]
changes not there in updated package, still same, only package.json shows version change
```
import { ModuleWithProviders } from '@angular/core';
export declare class SocialLoginModule {
    static forRoot(): ModuleWithProviders;
}

```

**Comment by sarfarazansari** [comment]
@balvinder294 issue is [fixed on this commit](https://github.com/sarfarazansari/ng-social-login-module/commit/10cc4ba803ed26bc9fc47c658704fe49a640c6e4) you can use library now make sure version should be `1.0.5`

**Comment by balvinder294** [comment]
Ohk thanks, i will check it again , integrating.
